### ISSUE TITLE
Commando value and disconnected devices

### ISSUE THREAD

**Issue by arjen8** [galadril/DomoticzForAndroid#61] opened 2015-12-03 07:43 UTC
Hi guys,

I was curious about the progress you made with this great app, so I compiled my own apk to test with. I hope you don't mind I did this, due to the fact that the app isn't official released yet.

First of all, the app works great. Very fast and useful!

I discovered two little issues while using the app:
- The commando value in the timer settings isn't right (on = off, and off = on)
- I disconnected my wall plug from the wall socket (so the wall plug is 'offline'). When I want to view the corresponding utility graphs, I get an error 'Could not get log data...' (this is correct), but the loading message is still visible. So I need to restart the app to continu.

One question: Is it right that scenes aren't presented yet on the dashboard? Is this een Work in Progress?

Keep up the good work!

**Comment by galadril** [comment] 2015-12-03 08:11
"One question: Is it right that scenes aren't presented yet on the dashboard? Is this een Work in Progress?"

No that's not correct, i've created a issue for it: #62 

We'll look into the other issues..

**Comment by RoadXY** [comment] 2015-12-03 08:14
I created a test switch with an timer and the popup dialog seems to be right.

**Comment by arjen8** [comment] 2015-12-03 08:18
![image](https://cloud.githubusercontent.com/assets/11772754/11555179/98a20758-999e-11e5-9614-9c0aa2d33c61.png)
Domoticz

![screenshot_2015-12-03-09-16-15](https://cloud.githubusercontent.com/assets/11772754/11555245/2654ad12-999f-11e5-80e3-46bd8fc2c9fd.jpeg)
App

**Comment by RoadXY** [comment] 2015-12-03 08:21
Ah, now I get it.
Thanks for the screenshots. 
Please add as much information and screenshots as possible in the opening post to clarify!

Confirmed the bug.

**Comment by galadril** [comment] 2015-12-03 09:33
The on/off command is fixed in the next version

![untitled](https://cloud.githubusercontent.com/assets/14561640/11556783/3f2dc8dc-99a9-11e5-9fde-300cb8fe642d.png)
![screenshot_20151203-103138](https://cloud.githubusercontent.com/assets/14561640/11556784/3f2f6278-99a9-11e5-99e1-0ddf24a7472c.png)

**Comment by galadril** [comment] 2015-12-03 09:45
" I get an error 'Could not get log data...' (this is correct), but the loading message is still visible. "
Ill also fix this in the next release

**Comment by arjen8** [comment] 2015-12-03 09:49
Great job!

**Comment by RoadXY** [comment] 2015-12-03 10:04
Found a type: it's not Commando but Command ;-)

**Comment by galadril** [comment] 2015-12-03 10:14
:-) type or typo??

**Closed as completed by galadril** 2015-12-03 10:14 UTC

**Comment by RoadXY** [comment] 2015-12-03 10:22
Typo in the type?
Typo found!
